# This file is a template, and might need editing before it works on your project.
image: golang:latest

variables:
  # Please edit to your GitLab project
  REPO_NAME: gitlab.aws.dev/devops-aws/tecli

# The problem is that to be able to use go get, one needs to put
# the repository in the $GOPATH. So for example if your gitlab domain
# is gitlab.com, and that your repository is namespace/project, and
# the default GOPATH being /go, then you'd need to have your
# repository in /go/src/gitlab.com/namespace/project
# Thus, making a symbolic link corrects this.
before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - info
  - build
  - release

info:
  stage: info
  script:
    - make go/version go/env

build:
  stage: build
  script:
    - make gitlab/build
  artifacts:
    paths:
      - build/tecli

release:
  only:
    refs:
      - master
      - tags
  stage: release
  script:
    - make gitlab/build gitlab/release
  artifacts:
    paths:
      - dist/tecli-*
